build:
    pyinstaller:
        args:
            - --collect-data=sv_ttk
description: This is a tconversation application, using the microsoft/phi-2 model.
models:
    - addtobinaryfile: false
      class: PhiForCausalLM
      isdownloaded: false
      module: transformers
      name: microsoft/phi-2
      options: {}
      path: models\microsoft\phi-2\model
      pipelinetag: text-generation
      source: hugging_face
      tokenizers:
        - class: AutoTokenizer
          options: {}
          path: models\microsoft\phi-2\AutoTokenizer
      version: "2024-02-06T12:36:24.000Z"
name: conversation-gui
sdk-tag: v1.1.0
update-suggested: true
version: 1.0.0
