build:
    pyinstaller:
        args:
            - --collect-data=sv_ttk
description: This is a tconversation application, using the microsoft/phi-2 model.
models:
    - name: microsoft/phi-2
      path: models/microsoft/phi-2/model
      module: transformers
      class: PhiForCausalLM
      options: {}
      tokenizers:
        - path: models/microsoft/phi-2/AutoTokenizer
          class: AutoTokenizer
          options: {}
      pipelinetag: text-generation
      source: hugging_face
      addtobinaryfile: true
      isdownloaded: true
      version: "2024-02-06T12:36:24.000Z"
      accesstoken: ""
name: conversation-gui
sdk-tag: v1.1.3
update-suggested: true
version: 1.0.0
